### PR TITLE
Added atom_list factory

### PR DESCRIPTION
**Pull request by johnzl-777**
This was suggested by @plquera but considering we have factory functions for waveforms it would be nice to carry that functionality over to atom positions. 

If waveforms allow you to build them independently so should geometries. Without this users would have to go to the plain `ListOfLocations` object in the IR which is rather cumbersome. 

All I've done here is aliased `start.add_position` which already handles the decent variety of argument types to an `atom_list` function.

### CODE REVIEW

**Comment by weinbe58** [comment]
What's wrong instantiating the `ListOfLocations`?

**Comment by johnzl-777** [comment]
Ah I see I've overcomplicated things here, this could just alias to return `ListOfLocations().add_position(position, filling)`. Let me go ahead and do that.

I think Pedro's comment was with regards to some asymmetry in the factory API in that you can build your waveforms with stuff like `piecewise_linear(...)` but when you get to atom geometries you have to go through `start.add(...)` or if you truly go via `ListOfLocations(...)` it gets ugly very quickly.

**Comment by weinbe58** [comment]
But you can also add an entire list of positions to `start.add_position([pos1, pos2, pos3, ...])` Also if you want Bravais lattices just use one of them as the starting point

**Comment by Roger-luo** [comment]
don't provide 2nd API to do the same thing, no, please don't

**Comment by johnzl-777** [comment]
Look I'll back off this but it would just be a shorter way to create `ListOfLocations`. 

My understanding is the waveform factories were made so you didn't have to go through the IR directly or work with sequences all the time. (e.g. be tied to a level coupling and spatial modulation *just* to create a waveform).

Pedro just suggested having this to have something Bloqade.jl-like, just how we have the `rydberg_h` factor (#652 ) which masks the construction of the actual program.

**Comment by johnzl-777** [comment]
Going back to what I said earlier it's just addressing an asymmetry with how we have these nice individual functions for waveform generation so it *seemed* nice to have another one for atoms, but I can kind of see how it could be more of a pain on our end.

**Comment by johnzl-777** [comment]
I'd like to issue a correction from my end for the record, the remark that initializing the `ListOfLocations` from scratch would "get ugly" is inaccurate. I misinterpreted the type annotation, you can initialize a `ListOfLocations` with the same list of tuples as you would .add_position.

This renders this PR quite redundant.

**Pull request closed without merging**
