### PR TITLE
[Unitary hack] Improve docstrings , explain Argument in pragmas.py

### LINKED ISSUE #955: explain argument
https://github.com/QuEraComputing/bloqade-python/blob/142d349cefcc8fea93ad27d8d827b53a0b65b846/src/bloqade/builder/pragmas.py#L115

### PR DESCRIPTION
**Pull request by shubhusion**
Fixes #955 #957

### CODE REVIEW

**Comment by shubhusion** [comment]
@Roger-luo please review this also

**Comment by Roger-luo** [comment]
LGTM, I think this can be counted as 5 docstrings for a 20$ bounty.

**Comment by johnzl-777** [comment]
@shubhusion great work! Could you just run the linter so this passes CI? Thanks!

**Comment by shubhusion** [comment]
> @shubhusion great work! Could you just run the linter so this passes CI? Thanks! 

@johnzl-777 @Roger-luo done

**Review by weinbe58 — APPROVED** [review]
Great job!

**Pull request merged**
