### PR TITLE
Fix Bloqade Emulator Serialization

### PR DESCRIPTION
**Pull request by johnzl-777**
If the Bloqade program in question use a custom function for any waveform (for example, the [Floquet Dynamics](https://queracomputing.github.io/bloqade-python-examples/latest/examples/example-1-floquet/) tutorial) it can't be serialized and `save()` fails to work with the Bloqade emulator generated `LocalBatch`.

@weinbe58 and I had a brief discussion about this and it seems the only real option here (because you can't serialize arbitrary functions) is to not include the Emulator IR as part of the `LocalBatch` serialization which means losing the ability to rerun tasks upon deserialization.

### CODE REVIEW

**Review by weinbe58 — DISMISSED** [review]
You need to make the `emulator_ir` field optional

**Comment by johnzl-777** [comment]
@weinbe58 I just realized from the unit tests that this breaks the ability to do bitstrings because of its reliance on `emulator_ir.register.sites`, let me see if I can get a workaround going

**Comment by weinbe58** [comment]
Oh right the emulator ir is used to generate the geometry metadata

**Comment by weinbe58** [comment]
If you look over my PR this will fix the problem

**Comment by johnzl-777** [comment]
I think it best to preserve as much of the `emulator_ir` contents as possible to potentially allow running after serialization (should everything be serializable).

To that end I placed a "dummy" dictionary as the result of serializing a python function waveform. I opted to give a warning (as opposed to an exception which would kill the serialization) telling the user everything else can be preserved except for that waveform. 

My one concern is the deserialization requires I let the Sample Waveform type have `none` in its body so the resulting deserialized program still wouldn't be runnable. Perhaps it's worth including in the serialize/deserialize warning that results are calculable but the program is not executable if it has an arbitrary python function.

**Comment by johnzl-777** [comment]
The `NullWaveform` should be better than just passing `None` around but I think it would be nice if we could throw an exception when a `NullWaveform` is detected on rerun instead of just the warning upon deserialization.

**Review by weinbe58 — APPROVED** [review]
LGTM

**Pull request merged**
